#!/usr/bin/env python3
"""Emit Rocq tests for selection/zero-conversion cfg_target paths."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def z_list(values: list[str]) -> str:
    return "[" + "; ".join(values) + "]"


def header(case: str) -> str:
    return f"""(* Generated by emit_selection_tests.py; do not edit. *)
Require Import Coq.ZArith.ZArith.
Require Import Coq.Lists.List.
Require Import FloatTest.lib.FloatTestCommon.
Require Import FloatTest.cases.{case}.spec.
Import ListNotations.
Local Open Scope Z_scope.
"""


def emit_ctrl() -> None:
    case = "CS_Ctrl_Att_Rate"
    lines = [
        line.split()
        for line in (ROOT / f"FloatTest/vectors/{case}.txt").read_text().splitlines()
        if line
    ]
    blocks = [header(case)]
    for index, cols in enumerate(lines):
        assert len(cols) == 24
        inputs, outputs = cols[:9], cols[9:]
        args = " ".join(f"(f64 ({value}))" for value in inputs)
        groups = [outputs[i:i + 3] for i in range(0, 15, 3)]
        expected = "(" + ", ".join(z_list(group) for group in groups) + ")"
        blocks.append(
            f"""Example t_{index:04d} :
  ctrlAttRate_mode2_fun {args} = {expected}.
Proof. vm_compute. reflexivity. Qed.
"""
        )
    inputs, outputs = lines[0][:9], lines[0][9:]
    outputs = outputs.copy()
    outputs[0] = str(int(outputs[0]) ^ 1)
    groups = [outputs[i:i + 3] for i in range(0, 15, 3)]
    args = " ".join(f"(f64 ({value}))" for value in inputs)
    expected = "(" + ", ".join(z_list(group) for group in groups) + ")"
    blocks.append(
        f"""Example negative_control_wrong_expected :
  ctrlAttRate_mode2_fun {args} <> {expected}.
Proof. vm_compute. discriminate. Qed.
"""
    )
    output = ROOT / f"FloatTest/cases/{case}/tests.v"
    output.write_text("\n".join(blocks), encoding="utf-8", newline="\n")
    print(f"{output}: {len(lines)} positive + 1 negative")


def emit_ires() -> None:
    case = "CS_IRES_Attitude"
    lines = [
        line.split()
        for line in (ROOT / f"FloatTest/vectors/{case}.txt").read_text().splitlines()
        if line
    ]
    blocks = [header(case)]
    for index, cols in enumerate(lines):
        assert len(cols) == 10
        fs0, fs1 = cols[:2]
        old_fv, old_fu, new_fv, new_fu = (
            cols[2:4], cols[4:6], cols[6:8], cols[8:10]
        )
        expected = f"({z_list(new_fv)}, {z_list(new_fu)})"
        blocks.append(
            f"""Example t_{index:04d} :
  ires_no_sensor_fun {fs0} {fs1} {z_list(old_fv)} {z_list(old_fu)}
  = {expected}.
Proof. vm_compute. reflexivity. Qed.
"""
        )
    cols = lines[0]
    fs0, fs1 = cols[:2]
    old_fv, old_fu, new_fv, new_fu = cols[2:4], cols[4:6], cols[6:8], cols[8:10]
    wrong = new_fv.copy()
    wrong[0] = str(int(wrong[0]) ^ 1)
    blocks.append(
        f"""Example negative_control_wrong_expected :
  ires_no_sensor_fun {fs0} {fs1} {z_list(old_fv)} {z_list(old_fu)}
  <> ({z_list(wrong)}, {z_list(new_fu)}).
Proof. vm_compute. discriminate. Qed.
"""
    )
    output = ROOT / f"FloatTest/cases/{case}/tests.v"
    output.write_text("\n".join(blocks), encoding="utf-8", newline="\n")
    print(f"{output}: {len(lines)} positive + 1 negative")


def emit_track() -> None:
    case = "CS_Track_Atti"
    lines = [
        line.split()
        for line in (ROOT / f"FloatTest/vectors/{case}.txt").read_text().splitlines()
        if line
    ]
    blocks = [header(case)]
    for index, cols in enumerate(lines):
        assert len(cols) == 26
        inputs, outputs = cols[:11], cols[11:]
        args = " ".join(f"(f64 ({value}))" for value in inputs)
        groups = [outputs[i:i + 3] for i in range(0, 15, 3)]
        expected = "(" + ", ".join(z_list(group) for group in groups) + ")"
        blocks.append(
            f"""Example t_{index:04d} :
  trackAttitude_zero_conversion_fun {args} = {expected}.
Proof. vm_compute. reflexivity. Qed.
"""
        )
    inputs, outputs = lines[0][:11], lines[0][11:]
    outputs = outputs.copy()
    outputs[0] = str(int(outputs[0]) ^ 1)
    groups = [outputs[i:i + 3] for i in range(0, 15, 3)]
    args = " ".join(f"(f64 ({value}))" for value in inputs)
    expected = "(" + ", ".join(z_list(group) for group in groups) + ")"
    blocks.append(
        f"""Example negative_control_wrong_expected :
  trackAttitude_zero_conversion_fun {args} <> {expected}.
Proof. vm_compute. discriminate. Qed.
"""
    )
    output = ROOT / f"FloatTest/cases/{case}/tests.v"
    output.write_text("\n".join(blocks), encoding="utf-8", newline="\n")
    print(f"{output}: {len(lines)} positive + 1 negative")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "case",
        choices=("CS_Ctrl_Att_Rate", "CS_IRES_Attitude", "CS_Track_Atti"),
    )
    case = parser.parse_args().case
    {
        "CS_Ctrl_Att_Rate": emit_ctrl,
        "CS_IRES_Attitude": emit_ires,
        "CS_Track_Atti": emit_track,
    }[case]()


if __name__ == "__main__":
    main()
