#!/usr/bin/env python3
"""Emit Rocq tests for cfg_target fallback-path specs."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def f64_list(values: list[str]) -> str:
    return "[" + "; ".join(f"(f64 ({value}))" for value in values) + "]"


def z_list(values: list[str]) -> str:
    return "[" + "; ".join(values) + "]"


def emit_gyro() -> None:
    case = "CS_GyroData_Disposal"
    vector = ROOT / f"FloatTest/vectors/{case}.txt"
    output = ROOT / f"FloatTest/cases/{case}/tests.v"
    lines = [line.split() for line in vector.read_text().splitlines() if line]
    blocks = [f"""(* Generated by emit_fallback_tests.py; do not edit. *)
Require Import Coq.ZArith.ZArith.
Require Import Coq.Lists.List.
Require Import FloatTest.lib.FloatTestCommon.
Require Import FloatTest.cases.{case}.spec.
Import ListNotations.
Local Open Scope Z_scope.
"""]
    for index, cols in enumerate(lines):
        assert len(cols) == 14
        flags, history, current = cols[:4], cols[4:7], cols[7:10]
        stop, selected = cols[10], cols[11:14]
        args = " ".join(flags) + f" {f64_list(history)} {f64_list(current)}"
        expected = f"({stop}, {z_list(selected)})"
        blocks.append(
            f"""Example t_{index:04d} :
  gyro_history_fallback_fun {args} = {expected}.
Proof. vm_compute. reflexivity. Qed.
"""
        )
    cols = lines[0]
    flags, history, current = cols[:4], cols[4:7], cols[7:10]
    stop, selected = cols[10], cols[11:14]
    args = " ".join(flags) + f" {f64_list(history)} {f64_list(current)}"
    wrong = selected.copy()
    wrong[0] = str(int(wrong[0]) ^ 1)
    blocks.append(
        f"""Example negative_control_wrong_expected :
  gyro_history_fallback_fun {args} <> ({stop}, {z_list(wrong)}).
Proof. vm_compute. discriminate. Qed.
"""
    )
    output.write_text("\n".join(blocks), encoding="utf-8", newline="\n")
    print(f"{output}: {len(lines)} positive + 1 negative")


def emit_precession() -> None:
    case = "CS_PrecessionNutationCal"
    vector = ROOT / f"FloatTest/vectors/{case}.txt"
    output = ROOT / f"FloatTest/cases/{case}/tests.v"
    lines = [line.split() for line in vector.read_text().splitlines() if line]
    blocks = [f"""(* Generated by emit_fallback_tests.py; do not edit. *)
Require Import Coq.ZArith.ZArith.
Require Import Coq.Lists.List.
Require Import FloatTest.lib.FloatTestCommon.
Require Import FloatTest.cases.{case}.spec.
Import ListNotations.
Local Open Scope Z_scope.
"""]
    for index, cols in enumerate(lines):
        assert len(cols) == 13
        q, error, matrix = cols[:3], cols[3], cols[4:]
        args = " ".join(f"(f64 ({value}))" for value in q)
        expected = f"({error}, {z_list(matrix)})"
        blocks.append(
            f"""Example t_{index:04d} :
  precession_invalid_qjd_fun {args} = {expected}.
Proof. vm_compute. reflexivity. Qed.
"""
        )
    q, error, matrix = lines[0][:3], lines[0][3], lines[0][4:]
    args = " ".join(f"(f64 ({value}))" for value in q)
    wrong = matrix.copy()
    wrong[0] = str(int(wrong[0]) ^ 1)
    blocks.append(
        f"""Example negative_control_wrong_expected :
  precession_invalid_qjd_fun {args} <> ({error}, {z_list(wrong)}).
Proof. vm_compute. discriminate. Qed.
"""
    )
    output.write_text("\n".join(blocks), encoding="utf-8", newline="\n")
    print(f"{output}: {len(lines)} positive + 1 negative")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "case", choices=("CS_GyroData_Disposal", "CS_PrecessionNutationCal")
    )
    case = parser.parse_args().case
    emit_gyro() if case == "CS_GyroData_Disposal" else emit_precession()


if __name__ == "__main__":
    main()
