#!/usr/bin/env python3
"""Emit Rocq vector theorems for cfg_target ModeConvert cases."""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


def emit(case: str) -> None:
    vector_path = ROOT / f"FloatTest/vectors/{case}.txt"
    output_path = ROOT / f"FloatTest/cases/{case}/tests.v"
    lines = [line.split() for line in vector_path.read_text().splitlines() if line]
    function = f"modeConvert_{case.split('_', 1)[1]}_fun"
    header = f"""(* Generated by emit_mode_convert_tests.py; do not edit. *)
Require Import Coq.ZArith.ZArith.
From SimpleC.SL Require Import FloatLib.
From Flocq.IEEE754 Require Import BinarySingleNaN Binary Bits.
Require Import FloatTest.lib.FloatTestCommon.
Require Import FloatTest.cases.{case}.spec.
Local Open Scope Z_scope.
"""
    blocks = [header]
    for index, cols in enumerate(lines):
        if case == "ModeConvert_EIM":
            assert len(cols) == 4
            timer, end_time, initial, expected = cols
            args = f"(f64 ({timer})) (f64 ({end_time})) {initial}"
        else:
            assert len(cols) == 5
            star, reference, inject, initial, expected = cols
            args = (
                f"(f64 ({star})) (f64 ({reference})) "
                f"(f64 ({inject})) {initial}"
            )
        blocks.append(
            f"""Example t_{index:04d} :
  {function} {args} = {expected}.
Proof. vm_compute. reflexivity. Qed.
"""
        )
    first = lines[0]
    if case == "ModeConvert_EIM":
        timer, end_time, initial, expected = first
        args = f"(f64 ({timer})) (f64 ({end_time})) {initial}"
    else:
        star, reference, inject, initial, expected = first
        args = (
            f"(f64 ({star})) (f64 ({reference})) "
            f"(f64 ({inject})) {initial}"
        )
    wrong = str(int(expected) ^ 1)
    blocks.append(
        f"""Example negative_control_wrong_expected :
  {function} {args} <> {wrong}.
Proof. vm_compute. discriminate. Qed.
"""
    )
    output_path.write_text("\n".join(blocks), encoding="utf-8", newline="\n")
    print(f"{output_path}: {len(lines)} positive + 1 negative")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "case", choices=("ModeConvert_EIM", "ModeConvert_SBM")
    )
    emit(parser.parse_args().case)


if __name__ == "__main__":
    main()
