#!/usr/bin/env python3
"""Emit Rocq tests for Gyro_Att_Predict and OrbitComputation specs."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def z_list(values: list[str]) -> str:
    return "[" + "; ".join(values) + "]"


def header(case: str) -> str:
    return f"""(* Generated by emit_remaining_cfg_tests.py; do not edit. *)
Require Import Coq.ZArith.ZArith.
Require Import Coq.Lists.List.
Require Import FloatTest.lib.FloatTestCommon.
Require Import FloatTest.cases.{case}.spec.
Import ListNotations.
Local Open Scope Z_scope.
"""


def emit_gyro() -> None:
    case = "CS_Gyro_Att_Predict"
    lines = [
        line.split()
        for line in (ROOT / f"FloatTest/vectors/{case}.txt").read_text().splitlines()
        if line
    ]
    blocks = [header(case)]
    for index, cols in enumerate(lines):
        assert len(cols) == 35
        inputs, outputs = cols[:14], cols[14:]
        args = " ".join(f"(f64 ({value}))" for value in inputs)
        groups = [
            outputs[:3], outputs[3:6], outputs[6:9], outputs[9:12],
            outputs[12:21],
        ]
        expected = "(" + ", ".join(z_list(group) for group in groups) + ")"
        blocks.append(
            f"""Example t_{index:04d} :
  gyroPredict_invalid_sequence_fun {args} = {expected}.
Proof. vm_compute. reflexivity. Qed.
"""
        )
    inputs, outputs = lines[0][:14], lines[0][14:]
    outputs = outputs.copy()
    outputs[0] = str(int(outputs[0]) ^ 1)
    groups = [
        outputs[:3], outputs[3:6], outputs[6:9], outputs[9:12],
        outputs[12:21],
    ]
    args = " ".join(f"(f64 ({value}))" for value in inputs)
    expected = "(" + ", ".join(z_list(group) for group in groups) + ")"
    blocks.append(
        f"""Example negative_control_wrong_expected :
  gyroPredict_invalid_sequence_fun {args} <> {expected}.
Proof. vm_compute. discriminate. Qed.
"""
    )
    output = ROOT / f"FloatTest/cases/{case}/tests.v"
    output.write_text("\n".join(blocks), encoding="utf-8", newline="\n")
    print(f"{output}: {len(lines)} positive + 1 negative")


def emit_orbit() -> None:
    case = "CS_OrbitComputation"
    lines = [
        line.split()
        for line in (ROOT / f"FloatTest/vectors/{case}.txt").read_text().splitlines()
        if line
    ]
    blocks = [header(case)]
    for index, cols in enumerate(lines):
        assert len(cols) == 16
        floats, integers = cols[:6], cols[6:9]
        fv, no_insert, count = cols[9:12]
        w0i, lmdg = cols[12:15], cols[15]
        args = " ".join(f"(f64 ({value}))" for value in floats)
        args += " " + " ".join(integers)
        expected = f"({fv}, {no_insert}, {count}, {z_list(w0i)}, {lmdg})"
        blocks.append(
            f"""Example t_{index:04d} :
  orbitControl_fun {args} = {expected}.
Proof. vm_compute. reflexivity. Qed.
"""
        )
    cols = lines[0]
    floats, integers = cols[:6], cols[6:9]
    fv, no_insert, count = cols[9:12]
    w0i, lmdg = cols[12:15], cols[15]
    wrong = w0i.copy()
    wrong[0] = str(int(wrong[0]) ^ 1)
    args = " ".join(f"(f64 ({value}))" for value in floats)
    args += " " + " ".join(integers)
    expected = f"({fv}, {no_insert}, {count}, {z_list(wrong)}, {lmdg})"
    blocks.append(
        f"""Example negative_control_wrong_expected :
  orbitControl_fun {args} <> {expected}.
Proof. vm_compute. discriminate. Qed.
"""
    )
    output = ROOT / f"FloatTest/cases/{case}/tests.v"
    output.write_text("\n".join(blocks), encoding="utf-8", newline="\n")
    print(f"{output}: {len(lines)} positive + 1 negative")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "case", choices=("CS_Gyro_Att_Predict", "CS_OrbitComputation")
    )
    case = parser.parse_args().case
    emit_gyro() if case == "CS_Gyro_Att_Predict" else emit_orbit()


if __name__ == "__main__":
    main()
