#!/usr/bin/env python3
"""Emit Rocq tests for CS_AttCtrl_Propel/CS_ThrParamCfgX."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
VECTOR = ROOT / "FloatTest/vectors/CS_AttCtrl_Propel.txt"
OUTPUT = ROOT / "FloatTest/cases/CS_AttCtrl_Propel/tests.v"

HEADER = """(* Generated by emit_attctrl_propel_tests.py; do not edit. *)
Require Import Coq.ZArith.ZArith.
Require Import FloatTest.lib.FloatTestCommon.
Require Import FloatTest.cases.CS_AttCtrl_Propel.spec.
Local Open Scope Z_scope.
"""


def main() -> None:
    lines = [line.split() for line in VECTOR.read_text().splitlines() if line]
    blocks = [HEADER]
    for index, cols in enumerate(lines):
        assert len(cols) == 11
        mode, timer, start, *flags, expected = cols
        args = " ".join(
            [mode, f"(f64 ({timer}))", f"(f64 ({start}))", *flags]
        )
        blocks.append(
            f"""Example t_{index:04d} :
  cs_ThrParamCfgX_fun {args} = {expected}.
Proof. vm_compute. reflexivity. Qed.
"""
        )
    mode, timer, start, *flags, expected = lines[0]
    args = " ".join([mode, f"(f64 ({timer}))", f"(f64 ({start}))", *flags])
    wrong = str(int(expected) ^ 1)
    blocks.append(
        f"""Example negative_control_wrong_expected :
  cs_ThrParamCfgX_fun {args} <> {wrong}.
Proof. vm_compute. discriminate. Qed.
"""
    )
    OUTPUT.write_text("\n".join(blocks), encoding="utf-8", newline="\n")
    print(f"{OUTPUT}: {len(lines)} positive + 1 negative")


if __name__ == "__main__":
    main()
