#!/usr/bin/env python3
"""Emit Rocq tests for cfg_target target-attitude identity paths."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def z_list(values: list[str]) -> str:
    return "[" + "; ".join(values) + "]"


def emit(case: str) -> None:
    vector = ROOT / f"FloatTest/vectors/{case}.txt"
    output = ROOT / f"FloatTest/cases/{case}/tests.v"
    lines = [line.split() for line in vector.read_text().splitlines() if line]
    blocks = [f"""(* Generated by emit_target_attitude_tests.py; do not edit. *)
Require Import Coq.ZArith.ZArith.
Require Import Coq.Lists.List.
Require Import FloatTest.lib.FloatTestCommon.
Require Import FloatTest.cases.{case}.spec.
Import ListNotations.
Local Open Scope Z_scope.
"""]
    for index, cols in enumerate(lines):
        if case == "CS_TrgtAtt_EIM":
            assert len(cols) == 18
            inputs, cro, wri, wro = cols[:3], cols[3:12], cols[12:15], cols[15:18]
            function = "trgtAtt_EIM_identity_fun"
            expected = f"({z_list(cro)}, {z_list(wri)}, {z_list(wro)})"
        else:
            assert len(cols) == 28
            inputs = cols[:4]
            cro_si, cro = cols[4:13], cols[13:22]
            wri, wro = cols[22:25], cols[25:28]
            function = "trgtAtt_NWM_identity_fun"
            expected = (
                f"({z_list(cro_si)}, {z_list(cro)}, "
                f"{z_list(wri)}, {z_list(wro)})"
            )
        args = " ".join(f"(f64 ({value}))" for value in inputs)
        blocks.append(
            f"""Example t_{index:04d} :
  {function} {args} = {expected}.
Proof. vm_compute. reflexivity. Qed.
"""
        )
    cols = lines[0]
    if case == "CS_TrgtAtt_EIM":
        inputs, cro, wri, wro = cols[:3], cols[3:12], cols[12:15], cols[15:18]
        function = "trgtAtt_EIM_identity_fun"
        wrong = wro.copy()
        wrong[0] = str(int(wrong[0]) ^ 1)
        expected = f"({z_list(cro)}, {z_list(wri)}, {z_list(wrong)})"
    else:
        inputs, cro_si, cro = cols[:4], cols[4:13], cols[13:22]
        wri, wro = cols[22:25], cols[25:28]
        function = "trgtAtt_NWM_identity_fun"
        wrong = wro.copy()
        wrong[0] = str(int(wrong[0]) ^ 1)
        expected = (
            f"({z_list(cro_si)}, {z_list(cro)}, "
            f"{z_list(wri)}, {z_list(wrong)})"
        )
    args = " ".join(f"(f64 ({value}))" for value in inputs)
    blocks.append(
        f"""Example negative_control_wrong_expected :
  {function} {args} <> {expected}.
Proof. vm_compute. discriminate. Qed.
"""
    )
    output.write_text("\n".join(blocks), encoding="utf-8", newline="\n")
    print(f"{output}: {len(lines)} positive + 1 negative")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "case", choices=("CS_TrgtAtt_EIM", "CS_TrgtAtt_NWM_USU")
    )
    emit(parser.parse_args().case)


if __name__ == "__main__":
    main()
