#!/usr/bin/env python3
import os,sys
CASE="ThreeAxisController";ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)));vec=os.path.join(ROOT,"vectors",CASE+".txt");out=os.path.join(ROOT,"cases",CASE,"tests.v")
header='''(* Generated by emit_three_axis_tests.py; do not edit. *)
Require Import Coq.ZArith.ZArith.
Require Import Coq.Bool.Bool.
Require Import Coq.Lists.List.
From SimpleC.SL Require Import FloatLib.
From Flocq.IEEE754 Require Import BinarySingleNaN Binary Bits.
Require Import FloatTest.lib.FloatTestCommon.
Require Import FloatTest.cases.ThreeAxisController.spec.
Import ListNotations.
Local Open Scope Z_scope.
'''
def f(x):return f"(f32 ({x}%Z))"
def main():
 lines=[x.strip()for x in open(vec,encoding="utf-8")if x.strip()];o=[header]
 for i,line in enumerate(lines):
  c=line.split();assert len(c)==28,(i,len(c));args=" ".join(f(x)for x in c[1:16]);groups=[c[16:19],c[19:22],c[22:25],c[25:28]];rhs="("+", ".join("["+"; ".join(g)+"]"for g in groups)+")"
  o.append(f"\nExample t_{i:04d} :\n  threeAxisController_fun {args} = {rhs}.\nProof. vm_compute. reflexivity. Qed.\n")
 first=lines[0].split();c=first;args=" ".join(f(x)for x in c[1:16]);groups=[c[16:19],c[19:22],c[22:25],c[25:28]];groups[0]=groups[0].copy();groups[0][0]=str(int(groups[0][0])^1);wrong="("+", ".join("["+"; ".join(g)+"]"for g in groups)+")"
 o.append(f"\nExample negative_control_wrong_expected :\n  threeAxisController_fun {args} <> {wrong}.\nProof. vm_compute. discriminate. Qed.\n")
 open(out,"w",encoding="utf-8",newline="\n").write("\n".join(o));print(f"{out}: {len(lines)} tests")
if __name__=="__main__":main()
