From SimpleC.EE.QCP_demos_tutorial Require Import swap_simple4_strategy_goal swap_simple4_strategy_proof.

Module swap_simple4_Strategy_Correctness : swap_simple4_Strategy_Correct.
  Include swap_simple4_strategy_proof.
End swap_simple4_Strategy_Correctness.
