(* Generated by emit_selection_tests.py; do not edit. *)
Require Import Coq.ZArith.ZArith.
Require Import Coq.Lists.List.
Require Import FloatTest.lib.FloatTestCommon.
Require Import FloatTest.cases.CS_IRES_Attitude.spec.
Import ListNotations.
Local Open Scope Z_scope.

Example t_0000 :
  ires_no_sensor_fun 0 0 [1; 4] [7; 10]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0001 :
  ires_no_sensor_fun 0 0 [2; 5] [8; 11]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0002 :
  ires_no_sensor_fun 0 0 [3; 6] [9; 12]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0003 :
  ires_no_sensor_fun 0 0 [1; 4] [7; 10]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0004 :
  ires_no_sensor_fun 0 0 [2; 5] [8; 11]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0005 :
  ires_no_sensor_fun 0 0 [3; 6] [9; 12]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0006 :
  ires_no_sensor_fun 0 0 [1; 4] [7; 10]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0007 :
  ires_no_sensor_fun 0 0 [2; 5] [8; 11]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0008 :
  ires_no_sensor_fun 0 0 [3; 6] [9; 12]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0009 :
  ires_no_sensor_fun 0 0 [1; 4] [7; 10]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0010 :
  ires_no_sensor_fun 0 0 [2; 5] [8; 11]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0011 :
  ires_no_sensor_fun 0 0 [3; 6] [9; 12]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0012 :
  ires_no_sensor_fun 0 0 [1; 4] [7; 10]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0013 :
  ires_no_sensor_fun 0 0 [2; 5] [8; 11]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0014 :
  ires_no_sensor_fun 0 0 [3; 6] [9; 12]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0015 :
  ires_no_sensor_fun 0 0 [1; 4] [7; 10]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0016 :
  ires_no_sensor_fun 0 0 [2; 5] [8; 11]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0017 :
  ires_no_sensor_fun 0 0 [3; 6] [9; 12]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0018 :
  ires_no_sensor_fun 0 0 [1; 4] [7; 10]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0019 :
  ires_no_sensor_fun 0 0 [2; 5] [8; 11]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0020 :
  ires_no_sensor_fun 0 0 [3; 6] [9; 12]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0021 :
  ires_no_sensor_fun 0 0 [1; 4] [7; 10]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0022 :
  ires_no_sensor_fun 0 0 [2; 5] [8; 11]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0023 :
  ires_no_sensor_fun 0 0 [3; 6] [9; 12]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0024 :
  ires_no_sensor_fun 0 0 [1; 4] [7; 10]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0025 :
  ires_no_sensor_fun 0 0 [2; 5] [8; 11]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0026 :
  ires_no_sensor_fun 0 0 [3; 6] [9; 12]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0027 :
  ires_no_sensor_fun 0 0 [1; 4] [7; 10]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0028 :
  ires_no_sensor_fun 0 0 [2; 5] [8; 11]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example t_0029 :
  ires_no_sensor_fun 0 0 [3; 6] [9; 12]
  = ([0; 0], [0; 0]).
Proof. vm_compute. reflexivity. Qed.

Example negative_control_wrong_expected :
  ires_no_sensor_fun 0 0 [1; 4] [7; 10]
  <> ([1; 0], [0; 0]).
Proof. vm_compute. discriminate. Qed.
