(* Generated by emit_attctrl_propel_tests.py; do not edit. *)
Require Import Coq.ZArith.ZArith.
Require Import FloatTest.lib.FloatTestCommon.
Require Import FloatTest.cases.CS_AttCtrl_Propel.spec.
Local Open Scope Z_scope.

Example t_0000 :
  cs_ThrParamCfgX_fun 0 (f64 (13835058055282163712)) (f64 (0)) 0 0 0 0 0 2 0 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0001 :
  cs_ThrParamCfgX_fun 7 (f64 (13832806255468478464)) (f64 (4602678819172646912)) 1 0 0 3 0 1 0 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0002 :
  cs_ThrParamCfgX_fun 0 (f64 (13830554455654793216)) (f64 (4607182418800017408)) 0 1 0 6 0 2 0 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0003 :
  cs_ThrParamCfgX_fun 7 (f64 (13826050856027422720)) (f64 (4609434218613702656)) 1 1 0 9 0 3 0 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0004 :
  cs_ThrParamCfgX_fun 0 (f64 (0)) (f64 (4611686018427387904)) 0 0 1 0 0 2 0 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0005 :
  cs_ThrParamCfgX_fun 7 (f64 (4602678819172646912)) (f64 (0)) 1 0 1 3 0 0 0 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0006 :
  cs_ThrParamCfgX_fun 0 (f64 (4607182418800017408)) (f64 (4602678819172646912)) 0 1 1 6 0 1 0 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0007 :
  cs_ThrParamCfgX_fun 7 (f64 (4609434218613702656)) (f64 (4607182418800017408)) 1 1 1 9 0 2 0 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0008 :
  cs_ThrParamCfgX_fun 0 (f64 (4611686018427387904)) (f64 (4609434218613702656)) 0 0 0 0 0 2 1 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0009 :
  cs_ThrParamCfgX_fun 7 (f64 (13835058055282163712)) (f64 (4611686018427387904)) 1 0 0 3 0 4 1 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0010 :
  cs_ThrParamCfgX_fun 0 (f64 (13832806255468478464)) (f64 (0)) 0 1 0 6 0 0 1 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0011 :
  cs_ThrParamCfgX_fun 7 (f64 (13830554455654793216)) (f64 (4602678819172646912)) 1 1 0 9 0 1 1 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0012 :
  cs_ThrParamCfgX_fun 0 (f64 (13826050856027422720)) (f64 (4607182418800017408)) 0 0 1 0 0 2 1 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0013 :
  cs_ThrParamCfgX_fun 7 (f64 (0)) (f64 (4609434218613702656)) 1 0 1 3 0 3 1 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0014 :
  cs_ThrParamCfgX_fun 0 (f64 (4602678819172646912)) (f64 (4611686018427387904)) 0 1 1 6 0 4 1 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0015 :
  cs_ThrParamCfgX_fun 7 (f64 (4607182418800017408)) (f64 (0)) 1 1 1 9 0 0 1 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0016 :
  cs_ThrParamCfgX_fun 0 (f64 (4609434218613702656)) (f64 (4602678819172646912)) 0 0 0 0 1 2 0 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0017 :
  cs_ThrParamCfgX_fun 7 (f64 (4611686018427387904)) (f64 (4607182418800017408)) 1 0 0 3 1 2 0 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0018 :
  cs_ThrParamCfgX_fun 0 (f64 (13835058055282163712)) (f64 (4609434218613702656)) 0 1 0 6 1 3 0 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0019 :
  cs_ThrParamCfgX_fun 7 (f64 (13832806255468478464)) (f64 (4611686018427387904)) 1 1 0 9 1 4 0 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0020 :
  cs_ThrParamCfgX_fun 0 (f64 (13830554455654793216)) (f64 (0)) 0 0 1 0 1 2 0 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0021 :
  cs_ThrParamCfgX_fun 7 (f64 (13826050856027422720)) (f64 (4602678819172646912)) 1 0 1 3 1 1 0 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0022 :
  cs_ThrParamCfgX_fun 0 (f64 (0)) (f64 (4607182418800017408)) 0 1 1 6 1 2 0 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0023 :
  cs_ThrParamCfgX_fun 7 (f64 (4602678819172646912)) (f64 (4609434218613702656)) 1 1 1 9 1 3 0 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0024 :
  cs_ThrParamCfgX_fun 0 (f64 (4607182418800017408)) (f64 (4611686018427387904)) 0 0 0 0 1 2 1 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0025 :
  cs_ThrParamCfgX_fun 7 (f64 (4609434218613702656)) (f64 (0)) 1 0 0 3 1 0 1 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0026 :
  cs_ThrParamCfgX_fun 0 (f64 (4611686018427387904)) (f64 (4602678819172646912)) 0 1 0 6 1 1 1 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0027 :
  cs_ThrParamCfgX_fun 7 (f64 (13835058055282163712)) (f64 (4607182418800017408)) 1 1 0 9 1 2 1 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0028 :
  cs_ThrParamCfgX_fun 0 (f64 (13832806255468478464)) (f64 (4609434218613702656)) 0 0 1 0 1 2 1 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0029 :
  cs_ThrParamCfgX_fun 7 (f64 (13830554455654793216)) (f64 (4611686018427387904)) 1 0 1 3 1 4 1 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0030 :
  cs_ThrParamCfgX_fun 0 (f64 (13826050856027422720)) (f64 (0)) 0 1 1 6 1 0 1 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0031 :
  cs_ThrParamCfgX_fun 7 (f64 (0)) (f64 (4602678819172646912)) 1 1 1 9 1 1 1 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0032 :
  cs_ThrParamCfgX_fun 0 (f64 (4602678819172646912)) (f64 (4607182418800017408)) 0 0 0 0 0 2 0 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0033 :
  cs_ThrParamCfgX_fun 7 (f64 (4607182418800017408)) (f64 (4609434218613702656)) 1 0 0 3 0 3 0 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0034 :
  cs_ThrParamCfgX_fun 0 (f64 (4609434218613702656)) (f64 (4611686018427387904)) 0 1 0 6 0 4 0 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0035 :
  cs_ThrParamCfgX_fun 7 (f64 (4611686018427387904)) (f64 (0)) 1 1 0 9 0 0 0 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0036 :
  cs_ThrParamCfgX_fun 0 (f64 (13835058055282163712)) (f64 (4602678819172646912)) 0 0 1 0 0 2 0 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0037 :
  cs_ThrParamCfgX_fun 7 (f64 (13832806255468478464)) (f64 (4607182418800017408)) 1 0 1 3 0 2 0 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0038 :
  cs_ThrParamCfgX_fun 0 (f64 (13830554455654793216)) (f64 (4609434218613702656)) 0 1 1 6 0 3 0 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0039 :
  cs_ThrParamCfgX_fun 7 (f64 (13826050856027422720)) (f64 (4611686018427387904)) 1 1 1 9 0 4 0 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0040 :
  cs_ThrParamCfgX_fun 0 (f64 (0)) (f64 (0)) 0 0 0 0 0 2 1 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0041 :
  cs_ThrParamCfgX_fun 7 (f64 (4602678819172646912)) (f64 (4602678819172646912)) 1 0 0 3 0 1 1 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0042 :
  cs_ThrParamCfgX_fun 0 (f64 (4607182418800017408)) (f64 (4607182418800017408)) 0 1 0 6 0 2 1 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0043 :
  cs_ThrParamCfgX_fun 7 (f64 (4609434218613702656)) (f64 (4609434218613702656)) 1 1 0 9 0 3 1 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0044 :
  cs_ThrParamCfgX_fun 0 (f64 (4611686018427387904)) (f64 (4611686018427387904)) 0 0 1 0 0 2 1 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0045 :
  cs_ThrParamCfgX_fun 7 (f64 (13835058055282163712)) (f64 (0)) 1 0 1 3 0 0 1 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0046 :
  cs_ThrParamCfgX_fun 0 (f64 (13832806255468478464)) (f64 (4602678819172646912)) 0 1 1 6 0 1 1 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0047 :
  cs_ThrParamCfgX_fun 7 (f64 (13830554455654793216)) (f64 (4607182418800017408)) 1 1 1 9 0 2 1 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0048 :
  cs_ThrParamCfgX_fun 0 (f64 (13826050856027422720)) (f64 (4609434218613702656)) 0 0 0 0 1 2 0 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0049 :
  cs_ThrParamCfgX_fun 7 (f64 (0)) (f64 (4611686018427387904)) 1 0 0 3 1 4 0 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0050 :
  cs_ThrParamCfgX_fun 0 (f64 (4602678819172646912)) (f64 (0)) 0 1 0 6 1 0 0 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0051 :
  cs_ThrParamCfgX_fun 7 (f64 (4607182418800017408)) (f64 (4602678819172646912)) 1 1 0 9 1 1 0 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0052 :
  cs_ThrParamCfgX_fun 0 (f64 (4609434218613702656)) (f64 (4607182418800017408)) 0 0 1 0 1 2 0 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0053 :
  cs_ThrParamCfgX_fun 7 (f64 (4611686018427387904)) (f64 (4609434218613702656)) 1 0 1 3 1 3 0 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0054 :
  cs_ThrParamCfgX_fun 0 (f64 (13835058055282163712)) (f64 (4611686018427387904)) 0 1 1 6 1 4 0 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0055 :
  cs_ThrParamCfgX_fun 7 (f64 (13832806255468478464)) (f64 (0)) 1 1 1 9 1 0 0 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0056 :
  cs_ThrParamCfgX_fun 0 (f64 (13830554455654793216)) (f64 (4602678819172646912)) 0 0 0 0 1 2 1 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0057 :
  cs_ThrParamCfgX_fun 7 (f64 (13826050856027422720)) (f64 (4607182418800017408)) 1 0 0 3 1 2 1 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0058 :
  cs_ThrParamCfgX_fun 0 (f64 (0)) (f64 (4609434218613702656)) 0 1 0 6 1 3 1 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0059 :
  cs_ThrParamCfgX_fun 7 (f64 (4602678819172646912)) (f64 (4611686018427387904)) 1 1 0 9 1 4 1 = 1.
Proof. vm_compute. reflexivity. Qed.

Example negative_control_wrong_expected :
  cs_ThrParamCfgX_fun 0 (f64 (13835058055282163712)) (f64 (0)) 0 0 0 0 0 2 0 <> 5.
Proof. vm_compute. discriminate. Qed.
