From SimpleC.EE.Applications_human.fme_ge_gmp.gmp Require Import mpz_div_qr_strategy_goal mpz_div_qr_strategy_proof.

Module mpz_div_qr_Strategy_Correctness : mpz_div_qr_Strategy_Correct.
  Include mpz_div_qr_strategy_proof.
End mpz_div_qr_Strategy_Correctness.
