From SimpleC.EE.LLM_bench.Engineering.STSTransDataSave.r2 Require Import IP_STSTransDataSave__annotation_subagent_tmp_goal IP_STSTransDataSave__annotation_subagent_tmp_proof_auto IP_STSTransDataSave__annotation_subagent_tmp_proof_manual.

Module VC_Correctness : VC_Correct.
  Include char_array_strategy_proof.
  Include IP_STSTransDataSave__annotation_subagent_tmp_proof_auto.
  Include IP_STSTransDataSave__annotation_subagent_tmp_proof_manual.
End VC_Correctness.
