#!/usr/bin/env python3
"""Patch one solved split lemma into a scratch manual copy."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from manual_goal_utils import (
    check_rocq_file,
    ensure_unique_lemma_names,
    find_single_lemma_by_name,
    load_manifest,
    parse_manual_file,
)


def main() -> int:
    parser = argparse.ArgumentParser(description="Patch one split lemma into a scratch manual copy.")
    parser.add_argument("manifest", help="Path to manifest.json generated by split_manual_goals.py")
    parser.add_argument("split_file", help="Path to the single split Rocq file to merge")
    parser.add_argument("--output", help="Write the patched manual file to this path")
    parser.add_argument("--in-place", action="store_true", help="Rejected: official manuals are main-owned")
    parser.add_argument("--dry-run", action="store_true", help="Show unified diff without writing")
    args = parser.parse_args()

    manifest_path = Path(args.manifest).expanduser().resolve()
    manifest = load_manifest(manifest_path)
    source_file = Path(str(manifest["source_file"])).resolve()
    if not source_file.is_file():
        raise SystemExit(f"Source manual file not found: {source_file}")

    split_file = Path(args.split_file).expanduser().resolve()
    if not split_file.is_file():
        raise SystemExit(f"Split Rocq file not found: {split_file}")

    manifest_by_file = {
        str(Path(str(item["split_rocq_file"])).resolve()): item
        for item in manifest["lemmas"]
    }
    if str(split_file) not in manifest_by_file:
        raise SystemExit(f"Split Rocq file is not listed in manifest: {split_file}")
    manifest_entry = manifest_by_file[str(split_file)]

    check_rocq_file(split_file)

    split_text = split_file.read_text(encoding="utf-8")
    _split_prelude, split_lemmas = parse_manual_file(split_text)
    ensure_unique_lemma_names(split_lemmas)
    if len(split_lemmas) != 1:
        raise SystemExit(f"Expected exactly one lemma in split file: {split_file}")

    split_lemma = split_lemmas[0]
    split_name = str(split_lemma["name"])
    if split_name != str(manifest_entry["name"]):
        raise SystemExit(
            f"Split file lemma name mismatch: manifest expects {manifest_entry['name']}, got {split_name}"
        )
    if str(split_lemma["header_line"]) != str(manifest_entry["statement_header"]):
        raise SystemExit(
            "Split file statement header does not match the original manifest entry.\n"
            f"Expected: {manifest_entry['statement_header']}\n"
            f"Got:      {split_lemma['header_line']}"
        )

    source_text = source_file.read_text(encoding="utf-8")
    _source_prelude, source_lemmas = parse_manual_file(source_text)
    ensure_unique_lemma_names(source_lemmas)

    expected_order = [str(name) for name in manifest["lemma_order"]]
    current_order = [str(lemma["name"]) for lemma in source_lemmas]
    if current_order != expected_order:
        raise SystemExit(
            "Current manual file no longer matches the manifest lemma inventory.\n"
            f"Expected: {expected_order}\n"
            f"Current:  {current_order}"
        )

    source_lemma = find_single_lemma_by_name(source_lemmas, split_name)
    if str(source_lemma["header_line"]) != str(manifest_entry["statement_header"]):
        raise SystemExit(
            "Current manual file statement header no longer matches the manifest entry.\n"
            f"Expected: {manifest_entry['statement_header']}\n"
            f"Current:  {source_lemma['header_line']}"
        )

    start_offset = int(source_lemma["start_offset"])
    end_offset = int(source_lemma["end_offset"])
    patched_text = source_text[:start_offset] + str(split_lemma["block"]) + source_text[end_offset:]

    if args.dry_run:
        import difflib
        diff = difflib.unified_diff(
            source_text.splitlines(keepends=True),
            patched_text.splitlines(keepends=True),
            fromfile=str(source_file),
            tofile=str(source_file) + " (patched)",
        )
        sys.stdout.writelines(diff)
        return 0

    if args.in_place and args.output:
        raise SystemExit("Use either --in-place or --output, not both.")

    if args.in_place:
        raise SystemExit("Refusing --in-place: scripts must not overwrite official proof manuals")
    elif args.output:
        output_path = Path(args.output).expanduser().resolve()
        if output_path == source_file:
            raise SystemExit("Refusing to overwrite the source proof manual")
        output_path.parent.mkdir(parents=True, exist_ok=True)
    else:
        work_dir = Path(str(manifest["work_dir"])).resolve()
        output_path = work_dir / f"{source_file.stem}.patched{source_file.suffix}"

    output_path.write_text(patched_text, encoding="utf-8")
    print(f"Patched lemma {split_name} into {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
