#!/usr/bin/env python3
"""Verify that the merged proof manual preserves original goals and compiles."""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from manual_goal_utils import (
    added_forbidden_toplevels,
    check_rocq_file,
    check_rocq_file_with_deps,
    cleanup_work_dir,
    ensure_unique_lemma_names,
    lemma_by_name,
    load_manifest,
    manifest_coq_project,
    parse_manual_file,
    sorted_dependency_files,
)


def _path_is_inside(path: Path, parent: Path) -> bool:
    try:
        path.resolve().relative_to(parent.resolve())
        return True
    except ValueError:
        return False


def _workdir_contains_handoff_artifacts(manifest: dict, work_dir: Path) -> bool:
    for key in (
        "migrated_proof_manual_file",
        "migrated_task_local_scratch_lib_file",
    ):
        raw = manifest.get(key)
        if not raw:
            continue
        path = Path(str(raw)).resolve()
        if path.exists() and _path_is_inside(path, work_dir):
            return True
    return False


def main() -> int:
    parser = argparse.ArgumentParser(description="Verify the final *_manual.v against the split-time manifest.")
    parser.add_argument("manifest", help="Path to manifest.json generated by split_manual_goals.py")
    parser.add_argument("--keep-workdir", action="store_true", help="Force-keep the temporary work dir on disk (no copy-back). Useful for debugging when the manifest didn't request keep.")
    args = parser.parse_args()

    manifest_path = Path(args.manifest).expanduser().resolve()
    manifest = load_manifest(manifest_path)
    seed_file = Path(str(manifest["source_file"])).resolve()
    final_file_raw = manifest.get(
        "migrated_proof_manual_file",
        manifest.get("merged_proof_manual_file", manifest["source_file"]),
    )
    source_file = Path(str(final_file_raw)).resolve()
    work_dir = Path(str(manifest["work_dir"])).resolve()
    keep_dest_raw = manifest.get("keep_dest")
    keep_dest = Path(str(keep_dest_raw)).resolve() if keep_dest_raw else None

    if not seed_file.is_file():
        raise SystemExit(f"Seed manual file not found: {seed_file}")
    if not source_file.is_file():
        raise SystemExit(f"Merged proof manual file not found: {source_file}")

    seed_text = seed_file.read_text(encoding="utf-8")
    _seed_prelude, seed_lemmas = parse_manual_file(seed_text)
    seed_map = lemma_by_name(seed_lemmas)
    source_text = source_file.read_text(encoding="utf-8")
    _prelude, lemmas = parse_manual_file(source_text)
    ensure_unique_lemma_names(lemmas)
    if "Admitted." in source_text:
        raise SystemExit(f"Merged proof manual still contains Admitted: {source_file}")
    forbidden = added_forbidden_toplevels(seed_text, source_text)
    if forbidden:
        raise SystemExit(
            "Merged proof manual introduced forbidden top-level declaration(s): "
            + "; ".join(forbidden)
        )

    expected_order = [str(name) for name in manifest.get("source_lemma_order", manifest["lemma_order"])]
    current_order = [str(lemma["name"]) for lemma in lemmas]

    current_original_order = [name for name in current_order if name in set(expected_order)]
    if current_original_order != expected_order:
        raise SystemExit(
            "Lemma inventory mismatch.\n"
            f"Expected: {expected_order}\n"
            f"Current:  {current_original_order}"
        )

    manifest_headers = {
        str(item["name"]): str(item["statement_header"])
        for item in manifest.get("all_lemmas", manifest["lemmas"])
    }
    final_map = lemma_by_name(lemmas)
    for lemma_name in expected_order:
        lemma = final_map[lemma_name]
        lemma_name = str(lemma["name"])
        current_header = str(lemma["header_line"])
        expected_header = manifest_headers.get(lemma_name, str(seed_map[lemma_name]["header_line"]))
        if current_header != expected_header:
            raise SystemExit(
                "Lemma statement header mismatch.\n"
                f"Lemma:    {lemma_name}\n"
                f"Expected: {expected_header}\n"
                f"Current:  {current_header}"
            )

    dep_files: list[str] = []
    for raw in manifest.get("case_dependency_files", []):
        path = Path(str(raw)).resolve()
        if path.is_file():
            dep_files.append(str(path))
    migrated_dep_task_local_scratch_lib = manifest.get(
        "migrated_case_dependency_task_local_scratch_lib_file"
    )
    migrated_task_local_scratch_lib = manifest.get("migrated_task_local_scratch_lib_file")
    if migrated_dep_task_local_scratch_lib:
        dep_files.append(str(Path(str(migrated_dep_task_local_scratch_lib)).resolve()))
    elif migrated_task_local_scratch_lib:
        dep_files.append(str(Path(str(migrated_task_local_scratch_lib)).resolve()))
    sorted_dep_files = sorted_dependency_files(dep_files)

    compile_deferred = bool(
        manifest.get("migrated_manual_compile_deferred_until_main_lib_integration", False)
    )
    if compile_deferred:
        print(
            "Skipping helper-free manual compile until main integrates migrated "
            "helpers into common_case_formal_lib"
        )
    elif sorted_dep_files:
        project_context = manifest_coq_project(manifest)
        if project_context is not None:
            project_root, flags = project_context
            check_rocq_file_with_deps(
                source_file,
                sorted_dep_files,
                project_root=project_root,
                flags=flags,
            )
        else:
            check_rocq_file_with_deps(source_file, sorted_dep_files)
    else:
        project_context = manifest_coq_project(manifest)
        if project_context is not None:
            project_root, flags = project_context
            check_rocq_file_with_deps(
                source_file,
                [],
                project_root=project_root,
                flags=flags,
            )
        else:
            check_rocq_file(source_file)

    manifest_keep = bool(manifest.get("debug_keep_workdir", False))
    force_keep = bool(args.keep_workdir)
    contains_handoff_artifacts = _workdir_contains_handoff_artifacts(manifest, work_dir)

    if manifest_keep and keep_dest is None:
        raise SystemExit(
            "Manifest says debug_keep_workdir=true but keep_dest is null. "
            "The work dir would be silently deleted. Aborting; please re-run "
            "split_manual_goals.py with --keep-workdir DEST."
        )

    if manifest_keep:
        # Copy-back to the user-specified destination, then remove the tmp dir.
        if keep_dest.exists():
            shutil.rmtree(keep_dest)
        keep_dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(work_dir, keep_dest)
        cleanup_work_dir(work_dir)
        print(f"Verified {source_file}; copied work dir to {keep_dest} and removed tmp {work_dir}")
    elif force_keep:
        print(f"Verified {source_file}; kept tmp work dir {work_dir} (no copy-back requested at split time)")
    elif contains_handoff_artifacts:
        print(
            f"Verified {source_file}; kept tmp work dir {work_dir} because it "
            "contains migrated handoff artifacts for main integration"
        )
    else:
        cleanup_work_dir(work_dir)
        print(f"Verified {source_file} and removed work directory {work_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
