(* Generated by emit_mode_convert_tests.py; do not edit. *)
Require Import Coq.ZArith.ZArith.
From SimpleC.SL Require Import FloatLib.
From Flocq.IEEE754 Require Import BinarySingleNaN Binary Bits.
Require Import FloatTest.lib.FloatTestCommon.
Require Import FloatTest.cases.ModeConvert_SBM.spec.
Local Open Scope Z_scope.

Example t_0000 :
  modeConvert_SBM_fun (f64 (13840057050868544962)) (f64 (13837309855095848960)) (f64 (13831905535543004365)) 7 = 7.
Proof. vm_compute. reflexivity. Qed.

Example t_0001 :
  modeConvert_SBM_fun (f64 (13839662985901150044)) (f64 (13836927049127522468)) (f64 (13831410139583993610)) 8 = 8.
Proof. vm_compute. reflexivity. Qed.

Example t_0002 :
  modeConvert_SBM_fun (f64 (13838976186957976044)) (f64 (13836544243159195976)) (f64 (13830914743624982856)) 9 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0003 :
  modeConvert_SBM_fun (f64 (13838188057023186207)) (f64 (13836161437190869484)) (f64 (13830284239677150986)) 10 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0004 :
  modeConvert_SBM_fun (f64 (13837399927088396370)) (f64 (13835778631222542991)) (f64 (13829293447759129478)) 7 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0005 :
  modeConvert_SBM_fun (f64 (13837399927088396370)) (f64 (13835395825254216499)) (f64 (13828302655841107968)) 8 = 8.
Proof. vm_compute. reflexivity. Qed.

Example t_0006 :
  modeConvert_SBM_fun (f64 (13836611797153606533)) (f64 (13834967983289616302)) (f64 (13827311863923086459)) 9 = 9.
Proof. vm_compute. reflexivity. Qed.

Example t_0007 :
  modeConvert_SBM_fun (f64 (13837557553075354337)) (f64 (13834202371352963317)) (f64 (13831905535543004365)) 10 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0008 :
  modeConvert_SBM_fun (f64 (13836769423140564500)) (f64 (13833436759416310333)) (f64 (13831410139583993610)) 7 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0009 :
  modeConvert_SBM_fun (f64 (13835981293205774664)) (f64 (13832671147479657349)) (f64 (13830914743624982856)) 8 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0010 :
  modeConvert_SBM_fun (f64 (13835981293205774663)) (f64 (13831905535543004364)) (f64 (13830284239677150986)) 9 = 9.
Proof. vm_compute. reflexivity. Qed.

Example t_0011 :
  modeConvert_SBM_fun (f64 (13835193163270984827)) (f64 (13831139923606351380)) (f64 (13829293447759129478)) 10 = 10.
Proof. vm_compute. reflexivity. Qed.

Example t_0012 :
  modeConvert_SBM_fun (f64 (13833752011390226268)) (f64 (13830194167684603576)) (f64 (13828302655841107968)) 7 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0013 :
  modeConvert_SBM_fun (f64 (13832175751520646595)) (f64 (13828662943811297608)) (f64 (13827311863923086459)) 8 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0014 :
  modeConvert_SBM_fun (f64 (13834067263364142202)) (f64 (13827131719937991636)) (f64 (13831905535543004365)) 9 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0015 :
  modeConvert_SBM_fun (f64 (13834067263364142202)) (f64 (13825150136101948616)) (f64 (13831410139583993610)) 10 = 10.
Proof. vm_compute. reflexivity. Qed.

Example t_0016 :
  modeConvert_SBM_fun (f64 (13832491003494562529)) (f64 (13822087688355336680)) (f64 (13830914743624982856)) 7 = 7.
Proof. vm_compute. reflexivity. Qed.

Example t_0017 :
  modeConvert_SBM_fun (f64 (13830914743624982855)) (f64 (13815962792862112800)) (f64 (13830284239677150986)) 8 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0018 :
  modeConvert_SBM_fun (f64 (13828122511856013148)) (f64 (4588807732320345792)) (f64 (13829293447759129478)) 9 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0019 :
  modeConvert_SBM_fun (f64 (13823889128206284874)) (f64 (4597454643604897152)) (f64 (13828302655841107968)) 10 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0020 :
  modeConvert_SBM_fun (f64 (13823889128206284876)) (f64 (4600877379321698720)) (f64 (13827311863923086459)) 7 = 7.
Proof. vm_compute. reflexivity. Qed.

Example t_0021 :
  modeConvert_SBM_fun (f64 (13828753015803845016)) (f64 (4603309323120478784)) (f64 (13831905535543004365)) 8 = 8.
Proof. vm_compute. reflexivity. Qed.

Example t_0022 :
  modeConvert_SBM_fun (f64 (13825150136101948616)) (f64 (4604840546993784752)) (f64 (13831410139583993610)) 9 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0023 :
  modeConvert_SBM_fun (f64 (13815242216921733520)) (f64 (4606371770867090720)) (f64 (13830914743624982856)) 10 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0024 :
  modeConvert_SBM_fun (f64 (4598175219545276418)) (f64 (4607542706770207048)) (f64 (13830284239677150986)) 7 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0025 :
  modeConvert_SBM_fun (f64 (4598175219545276416)) (f64 (4608308318706860032)) (f64 (13829293447759129478)) 8 = 8.
Proof. vm_compute. reflexivity. Qed.

Example t_0026 :
  modeConvert_SBM_fun (f64 (4603579539098121010)) (f64 (4609073930643513016)) (f64 (13828302655841107968)) 9 = 9.
Proof. vm_compute. reflexivity. Qed.

Example t_0027 :
  modeConvert_SBM_fun (f64 (4606732058837280365)) (f64 (4609839542580166004)) (f64 (13827311863923086459)) 10 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0028 :
  modeConvert_SBM_fun (f64 (4602949035150289148)) (f64 (4610605154516818988)) (f64 (13831905535543004365)) 7 = 1.
Proof. vm_compute. reflexivity. Qed.

Example t_0029 :
  modeConvert_SBM_fun (f64 (4606101554889448496)) (f64 (4611370766453471972)) (f64 (13831410139583993610)) 8 = 1.
Proof. vm_compute. reflexivity. Qed.

Example negative_control_wrong_expected :
  modeConvert_SBM_fun (f64 (13840057050868544962)) (f64 (13837309855095848960)) (f64 (13831905535543004365)) 7 <> 6.
Proof. vm_compute. discriminate. Qed.
