; Converted from:
; - _CoqProject: -R Rocq/unifysl Logic
; - Rocq/_CoqProject: -R unifysl Logic
; - Rocq/unifysl/_CoqProject: -R . Logic
(coq.theory
 (name Logic)
 (modules
  ExportSolvers.Normalize
  ExportSolvers.Normalize_Para
  GeneralLogic.Base
  GeneralLogic.Complete.Canonical_Kripke
  GeneralLogic.Complete.Complete_Kripke
  GeneralLogic.Complete.ContextProperty
  GeneralLogic.Complete.ContextProperty_Kripke
  GeneralLogic.Complete.ContextProperty_Trivial
  GeneralLogic.Complete.Lindenbaum
  GeneralLogic.Complete.Lindenbaum_Kripke
  GeneralLogic.HenkinCompleteness
  GeneralLogic.KripkeModel
  GeneralLogic.ModelClass
  GeneralLogic.ProofTheory.BasicDeduction
  GeneralLogic.ProofTheory.BasicLogicEquiv
  GeneralLogic.ProofTheory.BasicSequentCalculus
  GeneralLogic.ProofTheory.ProofTheoryPatternsD1
  GeneralLogic.ProofTheory.TheoryOfSequentCalculus
  GeneralLogic.Semantics.Kripke
  GeneralLogic.ShallowEmbedded.ModelLanguage
  GeneralLogic.ShallowEmbedded.MonoPredicateAsLang
  GeneralLogic.ShallowEmbedded.PredicateAsLang
  HoareLogic.BigStepSemantics
  HoareLogic.ConcurrentSemantics_Angelic
  HoareLogic.GuardedHoareLogic
  HoareLogic.GuardedHoareTriple_Angelic
  HoareLogic.GuardedHoareTriple_TraceSemantics
  HoareLogic.HoareLogic
  HoareLogic.HoareTriple_BigStepSemantics
  HoareLogic.ImperativeLanguage
  HoareLogic.OperationalSemanticsGenerator
  HoareLogic.ProgramState
  HoareLogic.SimpleSmallStepSemantics
  HoareLogic.SmallStepSemantics
  HoareLogic.Sound_Basic
  HoareLogic.Sound_Frame
  HoareLogic.Sound_Imp
  HoareLogic.Sound_Resource_Angelic
  HoareLogic.Sound_Resource_TraceSemantics
  HoareLogic.Trace
  HoareLogic.TraceSemantics
  lib.Bijection
  lib.Bisimulation
  lib.CancelFoundation
  lib.Coqlib
  lib.Countable
  lib.Ensembles_ext
  lib.EnsemblesProperties
  lib.Equivalence_ext
  lib.List_Func_ext
  lib.NatChoice
  lib.PTree
  lib.register_typeclass
  lib.Relation_ext
  lib.RelationPairs_ext
  lib.Stream.SigStream
  lib.Stream.StreamFunctions
  lib.Stream.StreamSplit
  lib.StrongInduction
  lib.SublistT
  LogicGenerator.ConfigCompute
  LogicGenerator.ConfigDenot
  LogicGenerator.ConfigLang
  LogicGenerator.demo932.Interface
  LogicGenerator.Utils
  MetaLogicInj.ProofTheory.ProofRules
  MetaLogicInj.Semantics.Kripke
  MetaLogicInj.ShallowEmbedded.ModelLanguageMetaLogic
  MetaLogicInj.Sound.Sound_Kripke
  MetaLogicInj.Syntax
  MinimumLogic.Complete.Complete
  MinimumLogic.Complete.ContextProperty_Kripke
  MinimumLogic.Complete.Lindenbaum_Kripke
  MinimumLogic.Complete.Truth_Kripke
  MinimumLogic.DeepEmbedded.Complete_Kripke
  MinimumLogic.DeepEmbedded.KripkeSemantics
  MinimumLogic.DeepEmbedded.MinimumLanguage
  MinimumLogic.DeepEmbedded.MinimumLogic
  MinimumLogic.DeepEmbedded.Soundness
  MinimumLogic.ProofTheory.ExtensionTactic
  MinimumLogic.ProofTheory.Minimum
  MinimumLogic.ProofTheory.ProofTheoryPatterns
  MinimumLogic.ProofTheory.ProofTheoryPatternsP
  MinimumLogic.ProofTheory.RewriteClass
  MinimumLogic.ProofTheory.TheoryOfJudgement
  MinimumLogic.ProofTheory.TheoryOfSequentCalculus
  MinimumLogic.Semantics.Kripke
  MinimumLogic.Semantics.SemanticEquiv
  MinimumLogic.Semantics.Trivial
  MinimumLogic.ShallowEmbedded.ModelLanguageMinimumLogic
  MinimumLogic.Sound.Sound_Classical_Trivial
  MinimumLogic.Sound.Sound_Kripke
  MinimumLogic.Syntax
  PropositionalLogic.Complete.Canonical_Kripke
  PropositionalLogic.Complete.Complete_Trivial
  PropositionalLogic.Complete.ContextProperty_Kripke
  PropositionalLogic.Complete.ContextProperty_Trivial
  PropositionalLogic.Complete.Lindenbaum_Kripke
  PropositionalLogic.Complete.Lindenbaum_Trivial
  PropositionalLogic.Complete.Truth_Kripke
  PropositionalLogic.Complete.Truth_Trivial
  PropositionalLogic.DeepEmbedded.Complete_Classical_Trivial
  PropositionalLogic.DeepEmbedded.Complete_Kripke
  PropositionalLogic.DeepEmbedded.KripkeSemantics
  PropositionalLogic.DeepEmbedded.ProofTheories
  PropositionalLogic.DeepEmbedded.PropositionalLanguage
  PropositionalLogic.DeepEmbedded.Soundness
  PropositionalLogic.DeepEmbedded.TrivialSemantics
  PropositionalLogic.ProofTheory.Classical
  PropositionalLogic.ProofTheory.DeMorgan
  PropositionalLogic.ProofTheory.GodelDummett
  PropositionalLogic.ProofTheory.Intuitionistic
  PropositionalLogic.ProofTheory.ProofTheoryPatterns
  PropositionalLogic.ProofTheory.RewriteClass
  PropositionalLogic.ProofTheory.TheoryOfClassicalAxioms
  PropositionalLogic.ProofTheory.TheoryOfIteratedConnectives
  PropositionalLogic.ProofTheory.TheoryOfPropositionalConnectives
  PropositionalLogic.Semantics.Kripke
  PropositionalLogic.Semantics.Trivial
  PropositionalLogic.ShallowEmbedded.ModelLanguagePropositionalLogic
  PropositionalLogic.ShallowEmbedded.MonoPredicatePropositionalLogic
  PropositionalLogic.ShallowEmbedded.PredicatePropositionalLogic
  PropositionalLogic.Sound.Sound_Classical_Trivial
  PropositionalLogic.Sound.Sound_Kripke
  PropositionalLogic.Syntax
  QuantifierLogic.DeepEmbedded.FirstOrderLanguage
  QuantifierLogic.DeepEmbedded.FirstOrderLogic
  QuantifierLogic.ProofTheory.QuantifierLogic
  QuantifierLogic.ShallowEmbedded.PredicateAsBLang
  QuantifierLogic.ShallowEmbedded.PredicateQuantifierLogic
  QuantifierLogic.Syntax
  SeparationLogic.Complete.Canonical_Flat
  SeparationLogic.Complete.ContextProperty_Flat
  SeparationLogic.Complete.Lindenbaum_Flat
  SeparationLogic.Complete.Truth_Flat
  SeparationLogic.DeepEmbedded.FlatSemantics
  SeparationLogic.DeepEmbedded.Parameter
  SeparationLogic.DeepEmbedded.ParametricCompleteness
  SeparationLogic.DeepEmbedded.ParametricSeparationLogic
  SeparationLogic.DeepEmbedded.SeparationEmpLanguage
  SeparationLogic.DeepEmbedded.SeparationLanguage
  SeparationLogic.DeepEmbedded.SeparationLogicsInLiteratures
  SeparationLogic.Model.DownwardsClosure
  SeparationLogic.Model.OrderedSA
  SeparationLogic.Model.OSAExamples
  SeparationLogic.Model.OSAGenerators
  SeparationLogic.Model.SeparationAlgebra
  SeparationLogic.Model.UpwardsClosure
  SeparationLogic.ProofTheory.Corable
  SeparationLogic.ProofTheory.Deduction
  SeparationLogic.ProofTheory.DerivedRules
  SeparationLogic.ProofTheory.IterSepcon
  SeparationLogic.ProofTheory.RewriteClass
  SeparationLogic.ProofTheory.SeparationLogic
  SeparationLogic.ProofTheory.SeparationLogicExtension
  SeparationLogic.ProofTheory.TheoryOfCancel
  SeparationLogic.ProofTheory.TheoryOfSeparationAxioms
  SeparationLogic.ProofTheory.WandFrame
  SeparationLogic.Semantics.Down2Flat
  SeparationLogic.Semantics.DownUpSemantics_Fail
  SeparationLogic.Semantics.DownwardsSemantics
  SeparationLogic.Semantics.EmpSemantics
  SeparationLogic.Semantics.FlatSemantics
  SeparationLogic.Semantics.SemanticsExtension
  SeparationLogic.Semantics.StrongSemantics
  SeparationLogic.Semantics.Up2Flat
  SeparationLogic.Semantics.UpwardsSemantics
  SeparationLogic.Semantics.WeakSemantics
  SeparationLogic.ShallowEmbedded.Join2Sepcon
  SeparationLogic.ShallowEmbedded.Model2CoqPropEmp
  SeparationLogic.ShallowEmbedded.ModelLanguageSeparationLogic
  SeparationLogic.ShallowEmbedded.MonoPredicateSeparationLogic
  SeparationLogic.ShallowEmbedded.PredicateSeparationLogic
  SeparationLogic.Sound.Sound_DownUp_Fail
  SeparationLogic.Sound.Sound_Downwards
  SeparationLogic.Sound.Sound_Flat
  SeparationLogic.Sound.Sound_Flat_Corable
  SeparationLogic.Sound.Sound_Upwards
  SeparationLogic.Syntax
  ShallowQuantifierLogic.ModelConstrALL
  ShallowQuantifierLogic.ModelConstrEX
  ShallowQuantifierLogic.ProofTheory
  ShallowQuantifierLogic.Syntax))

(include_subdirs qualified)
