From SimpleC.EE.QCP_demos_tutorial Require Import swap_simple5_strategy_goal swap_simple5_strategy_proof.

Module swap_simple5_Strategy_Correctness : swap_simple5_Strategy_Correct.
  Include swap_simple5_strategy_proof.
End swap_simple5_Strategy_Correctness.
