(* Generated by emit_mode_convert_tests.py; do not edit. *)
Require Import Coq.ZArith.ZArith.
From SimpleC.SL Require Import FloatLib.
From Flocq.IEEE754 Require Import BinarySingleNaN Binary Bits.
Require Import FloatTest.lib.FloatTestCommon.
Require Import FloatTest.cases.ModeConvert_EIM.spec.
Local Open Scope Z_scope.

Example t_0000 :
  modeConvert_EIM_fun (f64 (13833932155375321088)) (f64 (13831680355561635840)) 3 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0001 :
  modeConvert_EIM_fun (f64 (13832040643531825480)) (f64 (13830914743624982856)) 4 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0002 :
  modeConvert_EIM_fun (f64 (13829743807721866526)) (f64 (13829743807721866526)) 5 = 5.
Proof. vm_compute. reflexivity. Qed.

Example t_0003 :
  modeConvert_EIM_fun (f64 (13825870712042327900)) (f64 (13828212583848560558)) 3 = 2.
Proof. vm_compute. reflexivity. Qed.

Example t_0004 :
  modeConvert_EIM_fun (f64 (13813080489100595688)) (f64 (13826681359975254589)) 4 = 2.
Proof. vm_compute. reflexivity. Qed.

Example t_0005 :
  modeConvert_EIM_fun (f64 (13829653735729319116)) (f64 (13824249416176474520)) 5 = 5.
Proof. vm_compute. reflexivity. Qed.

Example t_0006 :
  modeConvert_EIM_fun (f64 (13825690568057233080)) (f64 (13820826680459672944)) 3 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0007 :
  modeConvert_EIM_fun (f64 (13812179769175121568)) (f64 (13812179769175121568)) 4 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0008 :
  modeConvert_EIM_fun (f64 (4600156803381319436)) (f64 (4592590756007337008)) 5 = 2.
Proof. vm_compute. reflexivity. Qed.

Example t_0009 :
  modeConvert_EIM_fun (f64 (4605200834963974390)) (f64 (4598715651500560876)) 3 = 2.
Proof. vm_compute. reflexivity. Qed.

Example t_0010 :
  modeConvert_EIM_fun (f64 (13810738617294363008)) (f64 (4601778099247172816)) 4 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0011 :
  modeConvert_EIM_fun (f64 (4600336947366414256)) (f64 (4603759683083215832)) 5 = 5.
Proof. vm_compute. reflexivity. Qed.

Example t_0012 :
  modeConvert_EIM_fun (f64 (4605290906956521800)) (f64 (4605290906956521800)) 3 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0013 :
  modeConvert_EIM_fun (f64 (4608128174721765212)) (f64 (4606822130829827768)) 4 = 2.
Proof. vm_compute. reflexivity. Qed.

Example t_0014 :
  modeConvert_EIM_fun (f64 (4610019686565260822)) (f64 (4607767886751575574)) 5 = 2.
Proof. vm_compute. reflexivity. Qed.

Example t_0015 :
  modeConvert_EIM_fun (f64 (4605380978949069212)) (f64 (4608533498688228558)) 3 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0016 :
  modeConvert_EIM_fun (f64 (4608173210718038918)) (f64 (4609299110624881542)) 4 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0017 :
  modeConvert_EIM_fun (f64 (4610064722561534526)) (f64 (4610064722561534526)) 5 = 5.
Proof. vm_compute. reflexivity. Qed.

Example t_0018 :
  modeConvert_EIM_fun (f64 (4611821126416209019)) (f64 (4610830334498187510)) 3 = 2.
Proof. vm_compute. reflexivity. Qed.

Example t_0019 :
  modeConvert_EIM_fun (f64 (4612766882337956824)) (f64 (4611595946434840496)) 4 = 2.
Proof. vm_compute. reflexivity. Qed.

Example t_0020 :
  modeConvert_EIM_fun (f64 (4610109758557808232)) (f64 (4612023788399440692)) 5 = 5.
Proof. vm_compute. reflexivity. Qed.

Example t_0021 :
  modeConvert_EIM_fun (f64 (4611843644414345872)) (f64 (4612406594367767184)) 3 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0022 :
  modeConvert_EIM_fun (f64 (4612789400336093676)) (f64 (4612789400336093676)) 4 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0023 :
  modeConvert_EIM_fun (f64 (4613735156257841480)) (f64 (4613172206304420168)) 5 = 2.
Proof. vm_compute. reflexivity. Qed.

Example t_0024 :
  modeConvert_EIM_fun (f64 (4614680912179589284)) (f64 (4613555012272746660)) 3 = 2.
Proof. vm_compute. reflexivity. Qed.

Example t_0025 :
  modeConvert_EIM_fun (f64 (4612811918334230528)) (f64 (4613937818241073152)) 4 = 4.
Proof. vm_compute. reflexivity. Qed.

Example t_0026 :
  modeConvert_EIM_fun (f64 (4613757674255978332)) (f64 (4614320624209399644)) 5 = 5.
Proof. vm_compute. reflexivity. Qed.

Example t_0027 :
  modeConvert_EIM_fun (f64 (4614703430177726138)) (f64 (4614703430177726138)) 3 = 3.
Proof. vm_compute. reflexivity. Qed.

Example t_0028 :
  modeConvert_EIM_fun (f64 (4615649186099473942)) (f64 (4615086236146052630)) 4 = 2.
Proof. vm_compute. reflexivity. Qed.

Example t_0029 :
  modeConvert_EIM_fun (f64 (4616392280037990073)) (f64 (4615469042114379122)) 5 = 2.
Proof. vm_compute. reflexivity. Qed.

Example negative_control_wrong_expected :
  modeConvert_EIM_fun (f64 (13833932155375321088)) (f64 (13831680355561635840)) 3 <> 2.
Proof. vm_compute. discriminate. Qed.
