From QCIPCases.xizi.xizi_circular_area_force_write Require Import xizi_circular_area_force_write_goal xizi_circular_area_force_write_proof_auto xizi_circular_area_force_write_proof_manual.

Module VC_Correctness : VC_Correct.
  Include int_array_strategy_proof.
  Include uint_array_strategy_proof.
  Include undef_uint_array_strategy_proof.
  Include array_shape_strategy_proof.
  Include xizi_circular_area_force_write_proof_auto.
  Include xizi_circular_area_force_write_proof_manual.
End VC_Correctness.
