From QCIPCases.xizi.xizi_single_link_first Require Import xizi_single_link_first_goal xizi_single_link_first_proof_auto xizi_single_link_first_proof_manual.

Module VC_Correctness : VC_Correct.
  Include xizi_single_link_strategy_proof.
  Include xizi_single_link_first_proof_auto.
  Include xizi_single_link_first_proof_manual.
End VC_Correctness.
